### ISSUE TITLE
truncated output from GZIPInputStream

### ISSUE THREAD

**Issue by zdila** [ymnk/jzlib#12]
Please see https://code.google.com/p/android/issues/detail?id=63873 because JZlib seems to have the same issue.

**Comment by ymnk** [comment]
Thanks to a comment at https://code.google.com/p/android/issues/detail?id=63873#c6, we have understood what is the problem.  We will improve our implementation of GZIPInputStream.

**Comment by ymnk** [comment]
I have improved code to support a concatenated gzip stream. Please refer to https://github.com/ymnk/jzlib/commit/9c2c07f6bb8a553426322a68e28436a481536cf5, and try the branch https://github.com/ymnk/jzlib/tree/concatenated_gzip_streams .

**Comment by zdila** [comment]
Now it works correctly in my Android application. Thanks!
